/* Main.c file generated by New Project wizard
 *
 * Created:   Wed Jan 31 2024
 * Processor: AT89C51
 * Compiler:  SDCC for 8051
 */

 #include <8051.h>
 #include "topology_manager.h"
 
 #define SAVE_DATA P2_4
 __bit SAMPLE_DATA;
 __bit STORE_DATA;
 
 unsigned char quarter_ms = 0;
 unsigned int ms = 0;
 
 void T0_ISR(void) __interrupt(1){
     quarter_ms++;
     if(quarter_ms == 4){
         quarter_ms = 0;
         ms++;
         //SAMPLE_DATA = 1;
 
         if(ms == 1000){
             inc_seconds();
             SAMPLE_DATA = 1;
             ms = 0;
         }
 
         //SAVE_DATA = 1;
         if(!SAVE_DATA){
             while(!SAVE_DATA){}
             STORE_DATA = 1;
         }
 
     }
 
 }
 
 void t0isr_init(){
     TMOD = 0x02;
     IE = 0x82;
     TL0 = 6;
     TH0 = 6;
     TR0 = 1;
 
 }
 
 void main(void)
  {
     t0isr_init();
     lcd_init();
     i2c_init();
     SAMPLE_DATA = 1;
     //clear_eeprom();
 
     while (1){
         if(SAMPLE_DATA){
             measure_voltage();
             measure_current();
             calculate_power();
             calculate_energy();
             SAMPLE_DATA = 0;
         }
 
         if(STORE_DATA){
             store_data_eeprom();
             STORE_DATA = 0;
         }
     }
  }